# Site settings
title: Ai Collaborative
email: your-email@domain.com

url: https://acmotanya.github.io
description: "Architecture & Interior Design Collaborative"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: 'tomato'

# Footer settings
footer: Ai Collaborative

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/SBootstrap
  - title: facebook
    url:
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket
    url: http://bitbucket.org/jekyll
  - title: github
    url: https://github.com/IronSummitMedia/startbootstrap

# Build settings
markdown: kramdown
permalink: pretty
