# Site settings
title: Ai Collaborative
email: info@aicoll.com
#baseurl: "/AiColldark"
url: https://www.aicoll.com
description: "Ai Collaborative, Inc. is an award winning, multi-disciplinary architectural firm offering a full range of design services including commercial interior design and consistently ranks at the top of architectural and interior design firms in the Tampa Bay Area."


# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: 'tomato'

# Footer settings
footer: Ai Collaborative

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/
  - title: facebook
    url: https://www.facebook.com/aicollaborative/


# Build settings
markdown: kramdown
permalink: pretty
